### ISSUE TITLE
Pypi Release Action

### ISSUE THREAD

**Issue by haz** [AI-Planning/lifted-pddl#3]
Should be easy to automate the release of a new version to pypi whenever a new release is created. Happy to help with this if you'd like (I've done it recently for `macq`, `planutils`, etc.)

**Comment by TheAeryan** [comment]
That seems like a very good idea. Also, help is very much appreciated, since I have never done it before.

**Comment by TheAeryan** [comment]
I have already created the action, following the steps in https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries.
Additionally, I have set up the action so that the PyPI package version is automatically extracted from the release version tag, as explained in https://www.seanh.cc/2022/05/21/publishing-python-packages-from-github-actions/
This is my first time doing this. Do you think it is correct?

**Comment by haz** [comment]
Yep! If you look here at what `planutils` is doing...

https://github.com/AI-Planning/planutils/blob/main/.github/workflows/python-publish.yml

...you can see that it's essentially identical (with yours using a newer version). Also looks like you added the secret in the right place. Only further thing to suggest is you fill out the setup.py file. E.g., https://github.com/AI-Planning/planutils/blob/main/setup.py

Not sure if you can just ingest the toml that's there...

**Comment by TheAeryan** [comment]
According to the information in this [post](https://realpython.com/pypi-publish-python-package/), it seems that pyproject.toml should be enough for newer versions of Setuptools. Still, there might be an error (which I don't get in my machine) when building the project. If that is the case, I can add a minimal setup.py with the following contents:

# setup.py
 from setuptools import setup 
setup()

I suppose I can try to use the action next time I release a new version and, if it doesn't work, I can add setup.py.

**Comment by haz** [comment]
Aye, makes sense. Why not give it a spin with a new v1.0.2? It should trigger as soon as you create a new release.

**Comment by TheAeryan** [comment]
I have tried the Action but it doesn't work. I have changed the script (python-publish.yml) to the default one (where the version number is not extracted from the github tag) and it still doesn't work.

When running the action, I obtain the following error in `Build package`: 
```
ValueError: invalid pyproject.toml config: `project`.
configuration error: `project` must contain ['version'] properties`. 
```
However, pyproject.toml contains the project version, so I don't know why this error raises.

**Comment by haz** [comment]
Can you trigger another run? I've tried downgrading to Python 3.10.x

**Comment by haz** [comment]
Another thing to try might be deleting the setup.py. Noticing some projects don't have it included, and when they do it's fully fleshed out. Really shooting in the dark here since I think you've got the version set correctly, and I've never done pyproject.toml stuff before.

**Comment by TheAeryan** [comment]
Still doesn't work. I suppose I should use setup.cfg instead of pyproject.toml.

**Comment by TheAeryan** [comment]
I have tried you suggestion and changed pyproject.toml by setup.py and it works!

I am closing the issue. Thanks for your help ^^
